services:
  aelf-playground:
    image: aelfactory/aelf-playground
  playground-service:
    image: aelfactory/playground-service
  csharp-language-service:
    image: aelfactory/monacoroslyncompletionprovider
  frontend:
    image: cgr.dev/chainguard/nginx:latest
    volumes:
      - ./nginx.compose.conf:/etc/nginx/conf.d/nginx.default.conf
    ports:
      - 8080:8080